### ISSUE TITLE
Multi-Objective FoM Parallelization

### ISSUE THREAD

**Issue by siegel8** [kch3782/torcwa#10]
Has there been any consideration for parallelization when working with a multi-objective FoM? I've been able to successfully implement a basic for-loop for the multi-objective FoM (such as optimizing for different input angles or wavelengths). But this process is serial, so the time to run scales linearly with number of objectives.

**Comment by kch3782** [comment]
So far, parametric sweep or simulation distribution to Multi GPU have not been implemented, and you have to manually use a for loop. Multi GPU is also considered as a torcwa function, but it will take a long time for implementation because there are many complicated parts.

Thank you.
