### ISSUE TITLE
Increased GPU Memory Usage compared to reference paper

### ISSUE THREAD

**Issue by siegel8** [kch3782/torcwa#13]
I am running some tests on memory usage versus number of truncated Fourier orders and my memory usage seems much higher than I expected based on the TORCWA text. Specifically, I am running the structure in example 2 with the order number set to 41. My memory usage is about 21 GB of 25 GB available on an Nvidia RTX A-5000. But based on the text, the 2060 Super was able to run the 41x41 TFO, which has much less memory than 21 GB it appears that the simulation requires.

![image](https://user-images.githubusercontent.com/116845401/208191646-e9089b77-5104-4a42-b835-19a1be924d80.png)

Are there any possible reasons why the memory usage could be increased or ways to reduce it? I am running a slightly modified version of example 2, starting from a fresh kernel. Only modification was to remove the sweep of orders to just a single simulation of order 41,41.  

Correction, the simulation did not finish and ran into an out of memory issue. Given that the A5000 is roughly equivalent to the 3090, this seems to be a large inconsistency. 
![image](https://user-images.githubusercontent.com/116845401/208194707-4e2ec4f4-4948-4f86-a9da-0edccda75a56.png)

**Comment by kch3782** [comment]
Setting `order = [M, N]` in the code means making a truncated Fourier order of 2M+1 in the x direction and 2N+1 in the y direction. So, the total truncated Fourier order is (2M+1) x (2N+1).

Therefore, if you set `order = [41, 41]` in the code, the total truncated Fourier order becomes 83 x 83. If you want to set up a 41 x 41 TFO like the paper, you can write `order = [20, 20]` in the code.

Thank you.

**Comment by siegel8** [comment]
Ah, that makes sense. Thanks again for your assistance!
