### ISSUE TITLE
multiple patterns within a single layer

### ISSUE THREAD

**Issue by MahmutRuzi** [kch3782/torcwa#16]
Hello,
Thanks for sharing the code.  
Are there any way to include multiple patterns within the same layer ? For example, two rectangles (or ellipses) of the same height within a layer separated by a given distance d .  The idea is study the effect of coupling between these structures. One such example is shown in Figure 1 of this article https://doi.org/10.1002/adom.202200812.

**Comment by kch3782** [comment]
To combine two patterns, you can use the rcwa_geo.union(p1, p2) function as below.

`e1 = torcwa.rcwa_geo.ellipse(Rx1, Ry1, Cx1, Cy1, theta1)`
`e2 = torcwa.rcwa_geo.ellipse(Rx2, Ry2, Cx2, Cy2, theta2)`
`pattern = torcwa.rcwa_geo.union(e1,e2)`

Here, `Rx, Ry` are x- and y-direction radius, `Cx, Cy` are center point, and `theta` is rotation angle in radian (center of rotation is [Cx, Cy]).

Also, the functions `rcwa_geo.intersection(p1,p2)`, `rcwa_geo.difference(p1,p2)` are provided in rcwa_geo.

Thank you.

**Comment by MahmutRuzi** [comment]
Awesome !
Thank you for the quick response.
