### ISSUE TITLE
Topological optimization for unit cell smaller than source wavelength

### ISSUE THREAD

**Issue by raynjh** [kch3782/torcwa#24]
Dear author,

I have run the code for Example 6 (topology optimization) in the depository and noticed that an error occurs when the length of the geometry (Lx) is set to be smaller than the wavelength of the incident light, e.g. Lx=400nm, lambda=532nm.

In particular, the optimization loop only runs for one iteration before terminating. The following messages appear indicating an infinite value for some matrix in the calculation of the E and H fields in layer0:

Cell In[9], line 39
     36 rho_bar = torch.real(torch.fft.fftshift(torch.fft.ifft2(torch.fft.ifftshift(rho_fft*g_fft))))
     37 rho_tilda = 1/2 + torch.tanh(2*beta[it]*rho_bar-beta[it])/(2*np.math.tanh(beta[it]))
---> 39 FoM = objective_function(rho_tilda)
     40 FoM.backward()
     42 with torch.no_grad():

Cell In[8], line 9, in objective_function(rho)
      7 sim.set_incident_angle(inc_ang=inc_ang,azi_ang=azi_ang)
      8 layer0_eps = rho*silicon_eps + (1.-rho)
----> 9 sim.add_layer(thickness=layer0_thickness,eps=layer0_eps)
     10 sim.solve_global_smatrix()
     11 t1xx = sim.S_parameters(orders=[1,0],direction='forward',port='transmission',polarization='xx',ref_order=[0,0])

File ~\.conda\envs\torcwa\lib\site-packages\torcwa\rcwa.py:168, in rcwa.add_layer(self, thickness, eps, mu)
    166     self._eigen_decomposition_homogenous(eps,mu)
    167 else:
--> 168     self._eigen_decomposition()
    170 self._solve_layer_smatrix()

File ~\.conda\envs\torcwa\lib\site-packages\torcwa\rcwa.py:1236, in rcwa._eigen_decomposition(self)
   1234 # Eigen-decomposition
   1235 if self.stable_eig_grad is True:
-> 1236     kz_norm, E_eigvec = Eig.apply(torch.matmul(self.P[-1],self.Q[-1]))
   1237 else:
   1238     kz_norm, E_eigvec = torch.linalg.eig(torch.matmul(self.P[-1],self.Q[-1]))

File ~\.conda\envs\torcwa\lib\site-packages\torch\autograd\function.py:506, in Function.apply(cls, *args, **kwargs)
    503 if not torch._C._are_functorch_transforms_active():
    504     # See NOTE: [functorch vjp and autograd interaction]
    505     args = _functorch.utils.unwrap_dead_wrappers(args)
--> 506     return super().apply(*args, **kwargs)  # type: ignore[misc]
    508 if cls.setup_context == _SingleLevelFunction.setup_context:
    509     raise RuntimeError(
    510         'In order to use an autograd.Function with functorch transforms '
    511         '(vmap, grad, jvp, jacrev, ...), it must override the setup_context '
    512         'staticmethod. For more details, please see '
    513         'https://pytorch.org/docs/master/notes/extending.func.html')

File ~\.conda\envs\torcwa\lib\site-packages\torcwa\torch_eig.py:14, in Eig.forward(ctx, x)
     11 @staticmethod
     12 def forward(ctx,x):
     13     ctx.input = x
---> 14     eigval, eigvec = torch.linalg.eig(x)
     15     ctx.eigval = eigval.cpu()
     16     ctx.eigvec = eigvec.cpu()

RuntimeError: torch.linalg.eig: input tensor should not contain infs or NaNs.

This error does not occur for geometry sizes smaller than the wavelength when there is no topology optimization process involved. I tried to inspect the relevant lines in the python files but could not find any obvious errors.

Do you know if there is any change I should make to the code? Thank you very much.

**Comment by siegel8** [comment]
At a glance, the issue may be from the your figure of merit as it is attempting to optimize for the first +1 grating order, which does not exist in the unit cell you have described, only the 0th order mode exists. See the following page for more details on grating modes https://www.plymouthgrating.com/guidance/technical-notes/fundamentals/the-grating-equation/

Relevant line of code with reference to order +1.
t1xx = sim.S_parameters(**orders=[1,0**],direction='forward',port='transmission',polarization='xx',ref_order=[0,0])

For this unit cell, it should be orders=[0,0] to run. If you want to have more orders, you either need to change the dimensions or change the angle of incidence (and you can calculate the orders from the equations in the linked page.

**Comment by raynjh** [comment]
Thanks for pointing out the error. I changed the grating orders in the line of code and it works now.
