### ISSUE TITLE
GPU memory consumption

### ISSUE THREAD

**Issue by zhixwang** [kch3782/torcwa#9]
Hi authors, I have a question regarding memory consumption. 

I find that the GPU memory usage of the following code increases with the iteration number (length of `z`). I cannot understand why, but I suspect it has something to do with the 'sim.field_xy'. `requires_grad` is `True`.

```
I_total = 0.
for (i, z_prop) in enumerate(z):
    [Ex, Ey, Ez], [_, _, _] = sim.field_xy(2, torcwa.rcwa_geo.x, torcwa.rcwa_geo.y, z_prop)
    I_i = torch.abs(Ex)**2 + torch.abs(Ey)**2 + torch.abs(Ez)**2
    I_total += I_i
    del Ex, Ey, Ez, I_i
```

Do you have any idea of the possible reasons?

Many thanks!

**Comment by kch3782** [comment]
If you set requires_grad = True to calculate the gradient, iteration creates a graph for the gradient when calculating the cumulative sum of I values using Ex, Ey, and Ez. Even if the value is deleted using 'del ', this graph remains in memory.

**Comment by zhixwang** [comment]
Thanks for your quick reply. Now I understand the reason.

The problem is that I need to extract the field in volume (multiple xy-planes). Currently I have to write it in loops as above, because there is no other option. 

However, I can easily face the problem of "CUDA out of memory" because of the reason you explained.  As I am now using 3090TI, I cannot see any good solution except for switching to CPU computation. This is not ideal either because of the low computation speed of CPU.

Are there any other possibilities to save the memory of the GPU for such tasks with requires_grad=True?

Thanks!

**Comment by kch3782** [comment]
If you use the gradient accumulation method, it seems that memory can be saved. I've never tried this method, so I don't know the details, but I know this method can be used when the memory size is small in deep learning.

**Comment by zhixwang** [comment]
Thank you for your reply.
